openapi: 3.0.3
info:
  title: Swagger Profile Service - OpenAPI 3.0
  description: Profile service api
  contact:
    email: laczko.krisztian@yahoo.com
  version: 1.0.11
servers:
  - url: 'https://localhost:8081/api'
tags:
  - name: student
    description: Student related objects
paths:
  /student:
    get:
      tags:
        - student
      summary: List all registered students
      operationId: listStudents
      responses:
        '200':
          description: Successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDto'
      description: List all registered students.
    post:
      summary: Create new student
      operationId: postStudent
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '500':
          description: Internal Server Error
      description: Create new student.
      tags:
        - student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDto'
    put:
      summary: Update student
      operationId: putStudent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Update existing student.
      tags:
        - student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDto'
  '/student/{studentId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: studentId
        in: path
        required: true
    delete:
      summary: Delete student by id
      operationId: deleteStudentById
      description: Delete student by id.
      tags:
        - student
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    StudentDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 3
        email:
          type: string
          format: email
        address:
          type: string
          minLength: 3
      required:
        - name
        - email
