openapi: 3.0.3
info:
  title: Swagger Profile Service - OpenAPI 3.0
  description: |-
    Profile service api
  contact:
    email: laczko.krisztian@yahoo.com
  version: 1.0.11
servers:
  - url: https://localhost:8081/api
tags:
  - name: student
    description: Student related objects
paths:
  /student:
    get:
      tags:
        - student
      summary: List all registered students
      operationId: listStudents
      responses:
        '200':
          description: Successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email